version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/standalone/data/import
    volumes:
      - ./keycloack/realm-config.json:/opt/jboss/keycloak/standalone/data/import/realm-config.json:ro
    command: ["kc.sh", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=singleFile", "-Dkeycloak.migration.file=/opt/jboss/keycloak/standalone/data/import/realm-config.json"]
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD-SHELL", "nc -zv postgres 5432"]
      interval: 10s
      timeout: 10s
      retries: 5  
    depends_on:
      - postgres
    networks:
      - default  

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - default  


